### ISSUE TITLE
Moodle Integration Guide: Broken downloads page link

### ISSUE THREAD

**Issue by Novocastrian** [openequella/openequella.github.io#21]
"Navigate to the [Downloads Page](https://equella.github.io/IntegrationsDownloads.md) in the openEQUELLA Github Repository" throws a 404. Please fix the page to send users to the correct downloads page.

**Comment by edalex-ian** [comment]
Hi @Novocastrian ,

Thanks for reporting the issue.

I'm guessing (because it's the only place I find your above text), you're talking about the Moodle Integration Guide at https://equella.github.io/guides/MoodleIntegrationGuide.html

I'll update the title accordingly, but if incorrect please let me know.

Cheers.

**Comment by edalex-ian** [comment]
Addressed via #61 .
