### ISSUE TITLE
Advanced Scripting Encoding

### ISSUE THREAD

**Issue by mohannadhenno** [openequella/openequella.github.io#98]
Hi,

I am using the advanced scripting tool to fetch the metadata from an external URL and then populate the needed template. The function used for this is **utils.getConnection()** then after that I am using conn.getResponse(true) to fetch the data and populate the XML. Everything is working fine except for non-English data (for example Arabic) it data appears as encoded characters. I confirmed that the API (external URL) is returning the proper text. 

SAMPLE CODE:

```
var conn = utils.getConnection("EXTERNAL URL");
conn.addFormData("param1", "val1");
conn.addFormData("param2", "val2"); 

var response = conn.getResponse(true);	
logger.log(response.getAsText());
return response.getAsXml();
```

**Comment by edalex-ian** [comment]
Hi @mohannadhenno ,

Thanks for raising the issue.

Unfortunately such issues should be raised over in https://github.com/openequella/openEQUELLA repository, as this one is just for documentation.

Would it be possible for you to raise it again over there as a Bug, and completely the provided template? While doing so, it'd be great if you can provide an example URL that we could actually test this with (rather than just `"EXTERNAL URL"`).

Thank you.
